### ISSUE TITLE
PSR-18

### ISSUE THREAD

**Issue by g105b** [PhpGt/Fetch#34]
We have compatibility with PSR-7 and PHP-HTTP, and can probably implement PSR-18 without any fuss.

**Comment by Sotiris-k** [comment]
It would certainly be a good thing for those rare occassions where, for instance, cURL is not fully available.

**Comment by slepic** [comment]
Well, actualy I just realized that Gt\Fetch\Http implements Http\Client\HttpClient which in turn extends the PSR-18 Psr\Http\Client\ClientInterface already.
But if there was PSR-18 client injected as dependency, it would be really nice, because you can then get rid off all the mess with curl, and have users inject their preferred implementation of psr 18 client and this library can focus on the async part. Making it async http client over any psr 18 client. This seems much more flexible then an async http client that also, along the way, provides unnecesarily complicated implementation of psr 18 client.

**Comment by g105b** [comment]
It's been some time since I've added functionality to this repo, but I'm currently working on branch `89-async` to make many improvements, one of which is the change to making @slepic's suggestion: Fetch is now compatible with other Http\Client\HttpClient implementations, but does not try to implement it itself.

Will be released to v2 once I've completed the other compatibility improvements. 

Thanks and happy new year!
